language: node_js
node_js:
    - node

install:
    - npm install

script:
    - npm run build # However the changes are not published because the NPM package should be the same as the GitHub repository

deploy:
    provider: npm
    email: finesserus@gmail.com
    api_key: $NPM_TOKEN
    on:
        tags: true

notifications:
    email: false
